#!/bin/sh
# Start mdev for dynamic /dev population

case "$1" in
    start)
        echo -n "Starting mdev: "
        echo /sbin/mdev > /proc/sys/kernel/hotplug
        mdev -s
        echo "OK"
        ;;
    stop)
        echo -n "Stopping mdev: "
        echo "" > /proc/sys/kernel/hotplug
        echo "OK"
        ;;
    restart|reload)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
